import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
  return (

    <div className={styles.body_container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header_container}>
			<h1>Portfolio</h1>
		</header>

		<nav className={styles.nav_container}>
      <Link href="/blog" passHref>
			  <a className={styles.nav_links}>Blog</a>
		  </Link>

		  <Link href="/about" passHref>
			  <a className={styles.nav_links}>About</a>
		  </Link>

		  <Link href="/projects" passHref>
			  <a className={styles.nav_links}>Projects</a>
		  </Link>

		  <Link href="https://github.com/ggiande" passHref>
			  <a className={styles.nav_links}>Github</a>
		  </Link>
    </nav>

      <main className={styles.main_container}>
			<h1>Hello, I am Ethan!</h1>
			<pre className={styles.pre_code_container}>
                <p className={styles.code_container}>
                    👋 I am currently pursuing a Bachelors degree in Computer Science.
                </p>
                <p className={styles.code_container}>
                    💻 I am a Computer Science major at California State University Stanislaus.
                </p>   
                <p className={styles.code_container}>
                    💼 This summer, I will be interning at Hilmar Cheese Company. 
                </p>    
                <p className={styles.code_container}>
                    💬 I am the CSU Stanislaus Computer Science Club Treasurer. 
                </p>
                
                <div id={styles.input} className={styles.terminal}></div>
            </pre>
			<p>
				I have done several projects and participated in HackMerced VII.
        I am interested in Data Science, Software Engineering, 
        and Cybersecurity. 
			</p>
		</main>

    </div>
  )
}
